name: Rebase Pull Requests to master

on:
  push:
    branches:
      - master

jobs:
  rebase:
    runs-on: ubuntu-20.04
    steps:
      - uses: linhbn123/rebase-pull-requests@v1.0.1
        with:
          # PAT needed to trigger other workflows
          token: ${{ secrets.REBASE_PAT }}
